@baseUrl = http://localhost:3000/api

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test2@gmail.com",
  "password": "secret"
}

### Sign up
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Test User",
  "username": "Tester",
  "email": "test2@gmail.com",
  "password": "secret",
  "confirmPassword": "secret",
  "gender": "male",
  "age": 25
}