@baseUrl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0MSIsImlhdCI6MTc3OTYwMTk4NSwiZXhwIjoxNzgxMzI5OTg1fQ.52vn0pQtw7KiuHsS1Tiwuv0-_6ByQajv_75gHEycp0k

# Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "secret"
}

# Sign up
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Test User",
  "username": "Tester",
  "email": "test@gmail.com",
  "password": "secret",
  "gender": "male",
  "age": 25
}