@baseUrl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJUZXN0ZXIiLCJpYXQiOjE3Nzk3Njk2MjIsImV4cCI6MTc4MTQ5NzYyMn0.hJAEDXoCyQe2n8CzRhfsdtrGDYr1MvDP0snsd0J51S4
@postId = 10

### Get all posts
GET {{baseUrl}}/posts
Authorization: Bearer {{token}}

### Like a post
POST {{baseUrl}}/posts/{{postId}}/like
Authorization: Bearer {{token}}

### Unlike a post
DELETE {{baseUrl}}/posts/{{postId}}/like
Authorization: Bearer {{token}}

### Bookmark a post
POST {{baseUrl}}/posts/{{postId}}/bookmark
Authorization: Bearer {{token}}

### Unbookmark a post
DELETE {{baseUrl}}/posts/{{postId}}/bookmark
Authorization: Bearer {{token}}

### Add comment to a post
POST {{baseUrl}}/posts/{{postId}}/comments
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"comment_text": "Test from rest client!"
}
